services:
  alist-strm:
    build: .  # 添加这一行，指示 docker-compose 使用当前目录的 Dockerfile 构建镜像
    container_name: alist-strm
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
      - ./logs:/app/logs
      - ./data:/data
      - ./:/app  # 调试专属：将当前本地目录挂载到容器内的 /app 目录，实现代码热更新
    environment:
      - TZ=Asia/Shanghai